#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil html-style:nil

#+TITLE: Design Project
#+AUTHOR: Stephen Brown

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/stsb11/9-SC-LED">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week 1</a></li>
      <li><a href="2_Lesson.html">Week 2</a></li>
      <li><a href="3_Lesson.html">Week 3</a></li>
      <li><a href="4_Lesson.html">Week 4</a></li>
      <li><a href="5_Lesson.html">Week 5</a></li>
      <li><a href="6_Lesson.html">Week 6</a></li>
      <li><a href="assessment.html">Assessment</a></li>

    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Homework Tasks
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** 1. Sense it
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
- The drawer alarm uses a LDR as a sensor to detect when the drawer is open. 
- Research *three* other types of sensor that could be added to a circuit, and suggest a project they could be used for. 
- For each, find a picture from the web of the sensor. E.g. An ultrasonic distance sensor uses ultrasound to detect how far away objects are from it. 
- This could be used to make a reversing sensor for a car.
- Upload your work to the first badge in the homework section on BourneToLearn.com

** 2. Speak It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:
- The drawer alarm uses a small loudspeaker to alert the owner when it is triggered. 
- Read this page: https://www.bournetoinvent.com/projects/mp3/step_4.html 
- Open a new Word document and write the title: Sound.
- Underneath it, explain in your own words how a loudspeaker works.
- Copy and paste the picture of the speaker system at the top of this section (not the image of a loudspeaker by itself).
- Underneath this, identify which speaker is which in the photo you copied and pasted. 
- For each: Say why you think that is. For instance, you might say that the top speaker in the left and right enclosures are tweeters, because they are very small.
- Explain what the benefit of having this type of speaker is.
- Find another picture of a sound system online (Argos have a good range), and idenfity the speakers in it.
- Upload your work to the second badge in the homework section on BourneToLearn.com

** 3. House It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:
- The housing for the drawer alarm is made from laser-cut 3mm acrylic sheet, separated by some nuts and bolts. 
- Sketch designs for two different housings and label them. 
- They’ll still need to have the switch on the front, somewhere for the LDR and two LEDs, but how you design it is up to you. 
- Indicate approximate dimensions. 
- Think about: Where will the PCB go? What holds it together? What’s it made from? Where do the batteries go?
- Upload your work to the third badge in the homework section on BourneToLearn.com

