#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil html-style:nil

#+TITLE: Design Project
#+AUTHOR: Stephen Brown

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/stsb11/9-SC-LED">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week 1</a></li>
      <li><a href="2_Lesson.html">Week 2</a></li>
      <li><a href="3_Lesson.html">Week 3</a></li>
      <li><a href="4_Lesson.html">Week 4</a></li>
      <li><a href="5_Lesson.html">Week 5</a></li>
      <li><a href="6_Lesson.html">Week 6</a></li>
      <li><a href="assessment.html">Assessment</a></li>

    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Homework Tasks
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** 1. Joint it
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
- There are many ways to join two different pieces of wood, plastic or metal together. 
- Research and write a series of short paragraphs to describe and identify advantages/disadvantages for  each of: Nuts and bolts, screws, pop rivets, glue and welding. e.g.
- "Nails can be used to join two pieces of wood together by driving them from one piece of wood into the other with a hammer. 
- The advantage of using nails is the speed with which the materials can be joined together.
- A disadvantage of nails is that the wood can split, and that it is easy to hit the wood by accident, marking the surface”
- Upload your work to the first badge in the homework section on BourneToLearn.com

** 2. Light It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:
-  LEDs are everywhere! In our TVs, on electrical items, street lighting and illuminating our homes. 
- Research the history of the LED, and explain why they’re becoming more popular. 200 words.
- Upload your work to the second badge in the homework section on BourneToLearn.com

** 3. Cut or Print It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:
- The housing for the drawer alarm is made from laser-cut 3mm acrylic sheet, separated by some nuts and bolts. 
- Sketch designs for two different housings and label them. 
- They’ll still need to have the switch on the front, somewhere for the LDR and two LEDs, but how you design it is up to you. 
- Indicate approximate dimensions. 
- Think about: Where will the PCB go? What holds it together? What’s it made from? Where do the batteries go?
- Upload your work to the third badge in the homework section on BourneToLearn.com

- Laser cutting, water jet cutting and 3D printing are relatively new technologies. 
- Research each of them; for each one, write a little about how it works, and what they can be used for. 200 words total.
- Upload your work to the third badge in the homework section on BourneToLearn.com

